version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/tomcat9/build
permissions:
  - object: /home/ubuntu/tomcat9/build
    owner: ubuntu
    group: ubuntu
hooks:
  BeforInstall:
   - location: scripts/beforedeploy.sh
     runas: ubuntu       
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu