name: Build and Deploy Spring Boot to AWS EC2
# workflow 실행 조건
on:  
  push:
    branches: [ merge ]
    #merge 브런치 push 될 때 실행      


jobs: 
  test: 
    name: Hello test job! 
    runs-on: ubuntu-22.04.3 
    steps:
      - name: check out
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
           java-version: 11
           
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
        
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
